max_width = 80
use_small_heuristics = "Max"
comment_width = 80
wrap_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
normalize_comments = true
format_code_in_doc_comments = true
error_on_line_overflow = true
error_on_unformatted = true
merge_derives = true
newline_style = "Unix"
